version: '3'

services:
  tpm-calc:
    container_name: tpm-calc
    build:
      context: build
      args:
        http_proxy: ${http_proxy}
    user: ${UID}:${GID}
    volumes:
      - .:/share
    working_dir: /share
    entrypoint:
      - ./workflow.sh
      - --debug
    command:
      - run
      - --ref
      - ref/GRCm38_p4_TCF7.fasta.gz
      - --ref-gene-map
      - ref/GRCm38_p4_TCF7_gene_map.txt.gz
      - --input
      - input
      - --output
      - output
